name: Build and Deploy
on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:
    name: Build page
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/cache@v3
        with:
          path: _build/.jupyter_cache
          key: ${{ runner.os }}-jupyter-cache
          restore-keys: |
            ${{ runner.os }}-jupyter-cache

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt

      - run: echo $MAPBOX_ACCESS_TOKEN > .mapbox_token
        env:
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

      - name: Build 🔧
        run: make build

      - uses: actions/upload-artifact@v3
        if: always()
        name: Upload gtfs-reports
        with:
          name: build-report
          path: _build/html/reports

      - run: touch _build/html/.nojekyll

      - uses: actions/upload-artifact@v3
        with:
          name: page-html
          path: _build/html/
          retention-days: 3
          if-no-files-found: error

  deploy:
    name: Deploy page
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: page-html
          path: _build/html/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          branch: gh-pages
          folder: _build/html/

      - name: Notify Cloudflare pages
        run: curl -X POST "$CLOUDFLARE_PAGES_DEPLOY_URL"
        env:
          CLOUDFLARE_PAGES_DEPLOY_URL: ${{ secrets.CLOUDFLARE_PAGES_DEPLOY_URL }}
          
