name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/cache@v2
        with:
          path: _build/.jupyter_cache
          key: ${{ runner.os }}-jupyter-cache
          restore-keys: |
            ${{ runner.os }}-jupyter-cache

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt

      - run: echo $MAPBOX_ACCESS_TOKEN > .mapbox_token
        env:
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

      - name: Build 🔧
        run: make build

      - uses: actions/upload-artifact@v3
        name: Upload gtfs-reports
        with:
          name: build-report
          path: _build/html/gtfs-reports

      - run: touch _build/html/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: _build/html/
          
      - name: Notify Cloudflare pages
        run: curl -X POST "$CLOUDFLARE_PAGES_DEPLOY_URL"
        env:
          CLOUDFLARE_PAGES_DEPLOY_URL: ${{ secrets.CLOUDFLARE_PAGES_DEPLOY_URL }}
          
